// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZ04TzDpjpZV0-pyVU9WhVgEZUNbl5sk',
    appId: '1:781763091225:web:e0367bb3c6d17b3a018388',
    messagingSenderId: '781763091225',
    projectId: 'friendapp-73341',
    authDomain: 'friendapp-73341.firebaseapp.com',
    storageBucket: 'friendapp-73341.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNwNBmHn7gvM6LFTiILPtW4h6B8Ckgof0',
    appId: '1:781763091225:android:3ba76499cca952c9018388',
    messagingSenderId: '781763091225',
    projectId: 'friendapp-73341',
    storageBucket: 'friendapp-73341.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChWaH8KP3qaLcDR83PtYwRWr-CuTZVc1w',
    appId: '1:781763091225:ios:14ce8482a356bca7018388',
    messagingSenderId: '781763091225',
    projectId: 'friendapp-73341',
    storageBucket: 'friendapp-73341.appspot.com',
    iosBundleId: 'com.example.findTravelCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChWaH8KP3qaLcDR83PtYwRWr-CuTZVc1w',
    appId: '1:781763091225:ios:ff8ad0c4576c0cca018388',
    messagingSenderId: '781763091225',
    projectId: 'friendapp-73341',
    storageBucket: 'friendapp-73341.appspot.com',
    iosBundleId: 'com.example.findTravelCompanion.RunnerTests',
  );
}
